/**
 * Notification Types Constants
 * All notification alert types for admin and agent
 */

// Admin Notification Types
const ADMIN_NOTIFICATION_TYPES = {
  NEW_AGENT: 'admin.new_agent',
  AGENT_NEW_LISTING: 'admin.agent_new_listing',
  AGENT_UPDATE_LISTING: 'admin.agent_update_listing',
  AGENT_DELETE_LISTING: 'admin.agent_delete_listing',
  ADMIN_MESSAGE: 'admin.message',
  ADMIN_REVIEW: 'admin.review',
  FUTURE_BUYER_REQUEST: 'admin.future_buyer_request'
};

// Agent Notification Types
const AGENT_NOTIFICATION_TYPES = {
  LISTING_VIEW: 'agent.listing_view',
  LISTING_REVIEW: 'agent.review',
  LISTING_MESSAGE: 'agent.message',
  LISTING_APPROVED: 'agent.listing_approved',
  LISTING_REJECTED: 'agent.listing_rejected',
  AGENT_APPROVED: 'agent.agent_approved'
};

// All Notification Types
const NOTIFICATION_TYPES = {
  ...ADMIN_NOTIFICATION_TYPES,
  ...AGENT_NOTIFICATION_TYPES
};

// Notification Priority Levels
const NOTIFICATION_PRIORITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  URGENT: 'urgent'
};

// Notification Alert Types (for UI styling)
const NOTIFICATION_ALERT_TYPES = {
  SUCCESS: 'success',
  INFO: 'info',
  WARNING: 'warning',
  ERROR: 'error',
  PRIMARY: 'primary'
};

// Notification Type to Alert Type Mapping
const NOTIFICATION_TYPE_TO_ALERT = {
  // Admin notifications
  [ADMIN_NOTIFICATION_TYPES.NEW_AGENT]: NOTIFICATION_ALERT_TYPES.PRIMARY,
  [ADMIN_NOTIFICATION_TYPES.AGENT_NEW_LISTING]: NOTIFICATION_ALERT_TYPES.INFO,
  [ADMIN_NOTIFICATION_TYPES.AGENT_UPDATE_LISTING]: NOTIFICATION_ALERT_TYPES.INFO,
  [ADMIN_NOTIFICATION_TYPES.AGENT_DELETE_LISTING]: NOTIFICATION_ALERT_TYPES.WARNING,
  [ADMIN_NOTIFICATION_TYPES.ADMIN_MESSAGE]: NOTIFICATION_ALERT_TYPES.PRIMARY,
  [ADMIN_NOTIFICATION_TYPES.ADMIN_REVIEW]: NOTIFICATION_ALERT_TYPES.SUCCESS,
  [ADMIN_NOTIFICATION_TYPES.FUTURE_BUYER_REQUEST]: NOTIFICATION_ALERT_TYPES.INFO,
  
  // Agent notifications
  [AGENT_NOTIFICATION_TYPES.LISTING_VIEW]: NOTIFICATION_ALERT_TYPES.INFO,
  [AGENT_NOTIFICATION_TYPES.LISTING_REVIEW]: NOTIFICATION_ALERT_TYPES.SUCCESS,
  [AGENT_NOTIFICATION_TYPES.LISTING_MESSAGE]: NOTIFICATION_ALERT_TYPES.PRIMARY,
  [AGENT_NOTIFICATION_TYPES.LISTING_APPROVED]: NOTIFICATION_ALERT_TYPES.SUCCESS,
  [AGENT_NOTIFICATION_TYPES.LISTING_REJECTED]: NOTIFICATION_ALERT_TYPES.WARNING,
  [AGENT_NOTIFICATION_TYPES.AGENT_APPROVED]: NOTIFICATION_ALERT_TYPES.SUCCESS
};

// Notification Type to Priority Mapping
const NOTIFICATION_TYPE_TO_PRIORITY = {
  // Admin notifications
  [ADMIN_NOTIFICATION_TYPES.NEW_AGENT]: NOTIFICATION_PRIORITY.HIGH,
  [ADMIN_NOTIFICATION_TYPES.AGENT_NEW_LISTING]: NOTIFICATION_PRIORITY.MEDIUM,
  [ADMIN_NOTIFICATION_TYPES.AGENT_UPDATE_LISTING]: NOTIFICATION_PRIORITY.LOW,
  [ADMIN_NOTIFICATION_TYPES.AGENT_DELETE_LISTING]: NOTIFICATION_PRIORITY.MEDIUM,
  [ADMIN_NOTIFICATION_TYPES.ADMIN_MESSAGE]: NOTIFICATION_PRIORITY.HIGH,
  [ADMIN_NOTIFICATION_TYPES.ADMIN_REVIEW]: NOTIFICATION_PRIORITY.MEDIUM,
  [ADMIN_NOTIFICATION_TYPES.FUTURE_BUYER_REQUEST]: NOTIFICATION_PRIORITY.MEDIUM,
  
  // Agent notifications
  [AGENT_NOTIFICATION_TYPES.LISTING_VIEW]: NOTIFICATION_PRIORITY.LOW,
  [AGENT_NOTIFICATION_TYPES.LISTING_REVIEW]: NOTIFICATION_PRIORITY.MEDIUM,
  [AGENT_NOTIFICATION_TYPES.LISTING_MESSAGE]: NOTIFICATION_PRIORITY.HIGH,
  [AGENT_NOTIFICATION_TYPES.LISTING_APPROVED]: NOTIFICATION_PRIORITY.HIGH,
  [AGENT_NOTIFICATION_TYPES.LISTING_REJECTED]: NOTIFICATION_PRIORITY.HIGH,
  [AGENT_NOTIFICATION_TYPES.AGENT_APPROVED]: NOTIFICATION_PRIORITY.URGENT
};

// Notification Type Labels (for display)
const NOTIFICATION_TYPE_LABELS = {
  // Admin notifications
  [ADMIN_NOTIFICATION_TYPES.NEW_AGENT]: 'New Agent Registered',
  [ADMIN_NOTIFICATION_TYPES.AGENT_NEW_LISTING]: 'Agent Added New Listing',
  [ADMIN_NOTIFICATION_TYPES.AGENT_UPDATE_LISTING]: 'Agent Updated Listing',
  [ADMIN_NOTIFICATION_TYPES.AGENT_DELETE_LISTING]: 'Agent Deleted Listing',
  [ADMIN_NOTIFICATION_TYPES.ADMIN_MESSAGE]: 'New Message',
  [ADMIN_NOTIFICATION_TYPES.ADMIN_REVIEW]: 'New Review',
  [ADMIN_NOTIFICATION_TYPES.FUTURE_BUYER_REQUEST]: 'New Future Buyer Request',
  
  // Agent notifications
  [AGENT_NOTIFICATION_TYPES.LISTING_VIEW]: 'Listing Viewed',
  [AGENT_NOTIFICATION_TYPES.LISTING_REVIEW]: 'New Review',
  [AGENT_NOTIFICATION_TYPES.LISTING_MESSAGE]: 'New Message',
  [AGENT_NOTIFICATION_TYPES.LISTING_APPROVED]: 'Listing Approved',
  [AGENT_NOTIFICATION_TYPES.LISTING_REJECTED]: 'Listing Rejected',
  [AGENT_NOTIFICATION_TYPES.AGENT_APPROVED]: 'Agent Account Approved'
};

module.exports = {
  ADMIN_NOTIFICATION_TYPES,
  AGENT_NOTIFICATION_TYPES,
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITY,
  NOTIFICATION_ALERT_TYPES,
  NOTIFICATION_TYPE_TO_ALERT,
  NOTIFICATION_TYPE_TO_PRIORITY,
  NOTIFICATION_TYPE_LABELS
};

